# permissions for end users to edit helloworlds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: helloworld-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: hello-world-operator
    app.kubernetes.io/part-of: hello-world-operator
    app.kubernetes.io/managed-by: kustomize
  name: helloworld-editor-role
rules:
- apiGroups:
  - charts.dev
  resources:
  - helloworlds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - charts.dev
  resources:
  - helloworlds/status
  verbs:
  - get
